//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Info
    {
        public int Id { get; set; }
        public string Flight_name { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string Arrival_time { get; set; }
        public string Departure { get; set; }
        public string Flight_class { get; set; }
        public Nullable<decimal> Flight_Charges { get; set; }
        public Nullable<int> Seat { get; set; }
    }
}
